
package com.manage.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceImplService", targetNamespace = "http://service.manage.com/", wsdlLocation = "http://localhost:8888/WS_Server/findGame?wsdl")
public class WebServiceImplService
    extends Service
{

    private final static URL WEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.manage.service.WebServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.manage.service.WebServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/WS_Server/findGame?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/WS_Server/findGame?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public WebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceImplService() {
        super(WEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.manage.com/", "WebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns WebServiceImpl
     */
    @WebEndpoint(name = "WebServiceImplPort")
    public WebServiceImpl getWebServiceImplPort() {
        return super.getPort(new QName("http://service.manage.com/", "WebServiceImplPort"), WebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceImpl
     */
    @WebEndpoint(name = "WebServiceImplPort")
    public WebServiceImpl getWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.manage.com/", "WebServiceImplPort"), WebServiceImpl.class, features);
    }

}
