server:
  port: 8080 # Eureka实例端口号
eureka:
  instance:
    prefer-ip-address: false  # 主机的IP
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} # 服务实例设置为IP：端口号的形式
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka服务端地址
spring:
  application:
    name: shop-eureka-user # 应用名称